# Generated by Django 5.1.2 on 2024-10-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monTiGMagasin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_purchase',
        ),
        migrations.AddField(
            model_name='transaction',
            name='sale_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase'), ('unsold', 'Unsold Withdrawal')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
